---
snakefile: snpCalling
latency-wait: 60
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
# Cluster submission
jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
max-jobs-per-second: 1                 #Maximal number of cluster/drmaa jobs per second, default is 10, fractions allowed.
max-status-checks-per-second: 10       #Maximal number of job status checks per second, default is 10
jobs: 20                              #Use at most N CPU cluster/cloud jobs in parallel.
cluster: "sbatch --output=\"logs/{rule}/slurm_%x_%j.out\" --error=\"logs/{rule}/slurm_%x_%j.log\" -N 1 -n {resources.threads} --mem={resources.mem_mb} --time={resources.runtime} --parsable -p main -q std"
cluster-status: "./profile/status-sacct.sh" #  Use to handle timeout exception, do not forget to chmod +x
# singularity
use-singularity: True
singularity-args: "--bind {workflow.workdir}"
# Job resources
# For some reasons time needs quotes to be read by snakemake
default-resources:
  - mem_mb=1000
  - runtime="01:00:00"
  - threads=1
