channels:
    - anaconda
    - bioconda
dependencies:
    - python=3.7
    - numpy
    - pandas
    - pysam
    - jinja2
    - markdown
    - mdx_smartypants
    - matplotlib
    - scipy
    - samtools
    - bwa
